from pydantic import BaseModel, SerializeAsAny
from datetime import datetime, timezone

from domain.models.agent import AgentResponse, AgentRole
from domain.models.chat import ChatModelResponseSchema
from domain.models.graph import CreateGraphReviewRequest

class AgentResponseRecord(BaseModel):
    round: int
    agent_role: AgentRole
    agent_index: int | None = None
    response_schema: SerializeAsAny[ChatModelResponseSchema] | None = None
    """The typed payload instance, only available in-process: DB reads and
    dict round-trips rebuild the data from ``response_payload`` instead."""
    response_payload: dict
    input_message: str | None = None
    context_used: str | None = None
    input_tokens: int | None = None
    output_tokens: int | None = None
    total_tokens: int | None = None
    system_prompt: str | None = None

    @classmethod
    def from_response(cls, response: AgentResponse, round: int) -> "AgentResponseRecord":
        """Live ``AgentResponse`` -> persistable record. ``round`` is computed by
        the caller (the graph node, which knows the state and its offset)."""
        return cls(
            round=round,
            agent_role=response.agent_role,
            agent_index=response.agent_index,
            response_schema=response.response_schema,
            response_payload=response.response_schema.model_dump(),
            input_message=response.input_message,
            context_used=response.context_used,
            input_tokens=response.input_tokens,
            output_tokens=response.output_tokens,
            total_tokens=response.total_tokens,
            system_prompt=response.system_prompt,
        )


class GraphReviewRecord(BaseModel):
    """Complete record of a single review-graph execution."""
    run_id: str
    timestamp: str
    paper_id: str
    run_description: str | None = None
    decision: str | None
    total_rounds: int
    reviews: list[str] | None = None
    meta_review: dict | None
    area_chair_response: dict | None = None
    author_response: dict | None
    retrieval_metadata: dict | None
    graph_config: dict
    agent_runs: list[AgentResponseRecord]
    
    @classmethod
    def to_run_record_from_result(cls, result: dict, request: CreateGraphReviewRequest, run_id: str) -> "GraphReviewRecord":
        """Assemble a full ``RunRecord`` from a live graph result and its request.
        ``run_id`` and ``timestamp`` are generated by the caller (StoreService) —
        neither the graph result nor the request carries them."""
        agent_runs = [AgentResponseRecord.model_validate(run) for run in result.get("agent_runs", [])]
        return cls(
            run_id=run_id,
            timestamp=datetime.now(timezone.utc).isoformat(),
            paper_id=request.paper_id,
            run_description=request.run_description or None,
            decision=result.get("decision"),
            total_rounds=result.get("current_round", 0),
            reviews=result.get("reviews"),
            meta_review=result.get("meta_review"),
            area_chair_response=result.get("area_chair_response"),
            author_response=result.get("author_response"),
            retrieval_metadata=result.get("retrieval_metadata"),
            graph_config=request.graph_config.model_dump(),
            agent_runs=agent_runs,
        )


class GraphReviewSummary(BaseModel):
    """Lightweight version of RunRecord for the run-history list."""

    run_id: str
    timestamp: str
    paper_id: str
    run_description: str | None = None
    decision: str | None
    total_rounds: int
